<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <InternalsVisibleTo Include="BinAnalyzer.Tui.Tests" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\BinAnalyzer.Core\BinAnalyzer.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Terminal.Gui" Version="2.*" />
  </ItemGroup>

</Project>
