<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.*" />
    <PackageReference Include="xunit" Version="2.*" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.*">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="bunit" Version="2.*" />
    <PackageReference Include="FluentAssertions" Version="8.*" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\BinAnalyzer.Web\BinAnalyzer.Web.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\..\formats\wav.bdef.yaml" Link="formats\wav.bdef.yaml" CopyToOutputDirectory="PreserveNewest" />
    <None Include="..\..\formats\mp4.bdef.yaml" Link="formats\mp4.bdef.yaml" CopyToOutputDirectory="PreserveNewest" />
    <None Include="..\..\formats\common\riff.bdef.yaml" Link="formats\common\riff.bdef.yaml" CopyToOutputDirectory="PreserveNewest" />
    <None Include="..\..\formats\common\isobmff.bdef.yaml" Link="formats\common\isobmff.bdef.yaml" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

</Project>
